### ISSUE TITLE
How to use generated icon fonts?

### ISSUE THREAD

**Issue by glebsexy** [wavetogether/wave_figma#7]
Thanks for a cool plugin! I was able to export and install the font but now how do I find these icons in Figma? I assume they should be ligatures and they are even shown as ligatures in Type Details menu but when I simply type the name of the icon it doesn't work. I also tried typing some gibberish from the config.json file without success. What should I type to make it show the icon? Would be useful to add this info to the plugin description too.

**Comment by sunguard** [comment]
It might be the problem: the unicode is escaped or not. At that moment, the plugin exports escaped unicode for convenient view of config file; however, for now, the plugin exports unescaped unicode so that you can use it by pasting string of config file directly.

----

Sorry for the late response... :(
